TARGET = XCORE-AI-EXPLORER
APP_NAME =
XCC_FLAGS =  -g -O2 -report -fxscope \
             -fcomment-asm -Wno-bidirectional-buffered-port \
             -mcmodel=large
USED_MODULES =
SOURCE_DIRS = src

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

# Use the main Makefile from module_xmos_common
XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common



