#List models to be run and their parameters

model1:
  filename: "mobilenet_v1_0.25_128_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Int" #[Int, Ext, None]
  memorySecondary: "Ext" #[Int, Ext, None]
  loadType: "split" #[single, split]
  alpha: 0.25
  inputRes: 128 
model2:
  filename: "mobilenet_v1_0.25_160_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Int" #[Int, Ext, None]
  memorySecondary: "Ext" #[Int, Ext, None]
  loadType: "split" #[single, split]
  alpha: 0.25
  inputRes: 160 
model3:
  filename: "mobilenet_v1_0.25_192_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Int" #[Int, Ext, None]
  memorySecondary: "Ext" #[Int, Ext, None]
  loadType: "split" #[single, split]
  alpha: 0.25
  inputRes: 192
model4:
  filename: "mobilenet_v1_0.25_224_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
  alpha: 0.25
  inputRes: 224
model5:
  filename: "mobilenet_v1_0.5_128_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
  alpha: 0.5
  inputRes: 128
model6:
  filename: "mobilenet_v1_0.5_160_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
  alpha: 0.5
  inputRes: 160
model7:
  filename: "mobilenet_v1_0.5_192_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
  alpha: 0.5
  inputRes: 192
model8:
  filename: "mobilenet_v1_0.5_224_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
  alpha: 0.5
  inputRes: 224
model9:
  filename: "efficientnet_b0_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
model10:
  filename: "mobilenet_v2_0.35_xcore.tflite"
  flash: False #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Ext" #[Int, Ext, None]
  memorySecondary: "Int" #[Int, Ext, None]
  loadType: "single" #[single, split]
  alpha: 0.35
model11:
  filename: "mobilenet_v1_0.25_128.tflite"
  flash: True #Will put model+paramters in flash, expects filename.out in same dir as model
  loadToExt: False #If Flash, Whether to load Model to secondary memory
  memoryPrimary: "Int" #[Int, Ext, None]
  memorySecondary: "Ext" #[Int, Ext, None]
  loadType: "split" #[single, split]
  alpha: 0.25
  inputRes: 128 